apiVersion: v1
kind: Pod
metadata:
  name: crash-pod
spec:
  restartPolicy: Always
  containers:
    - name: crash-container
      image: busybox
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
        limits:
          cpu: "50m"
          memory: "32Mi"
      command: ["/bin/sh"]
      args:
        - "-c"
        - |
          echo "Starting Application..."
          sleep 2
          echo "Simulating failure. . ."
          exit 1
